//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	in.ShootController.DeepCopyInto(&out.ShootController)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GardenShootTrustConfiguratorConfiguration) DeepCopyInto(out *GardenShootTrustConfiguratorConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Controllers.DeepCopyInto(&out.Controllers)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GardenShootTrustConfiguratorConfiguration.
func (in *GardenShootTrustConfiguratorConfiguration) DeepCopy() *GardenShootTrustConfiguratorConfiguration {
	if in == nil {
		return nil
	}
	out := new(GardenShootTrustConfiguratorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GardenShootTrustConfiguratorConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShootControllerConfig) DeepCopyInto(out *ShootControllerConfig) {
	*out = *in
	if in.ResyncPeriod != nil {
		in, out := &in.ResyncPeriod, &out.ResyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShootControllerConfig.
func (in *ShootControllerConfig) DeepCopy() *ShootControllerConfig {
	if in == nil {
		return nil
	}
	out := new(ShootControllerConfig)
	in.DeepCopyInto(out)
	return out
}
