version: "2"
linters:
  default: standard
  # set of linters in addition to the default set (https://golangci-lint.run/usage/linters/#enabled-by-default)
  enable:
    - embeddedstructfieldcheck
    - gocritic
    - gosec
    - nilerr
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    revive:
      rules:
      # recommended rules https://github.com/mgechev/revive/tree/v1.9.0?tab=readme-ov-file#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
        arguments:
        - allowedPackages:
          - github.com/onsi/ginkgo
          - github.com/onsi/gomega
          - github.com/onsi/ginkgo/extensions/table
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
        - disableStutteringCheck
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      # - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      # - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  exclusions:
    generated: lax
    rules:
    # revive:
      - path: (.+)\.go$
        text: var-naming # ((var|const|struct field|func) .* should be .*
      - path: (.+)\.go$
        text: dot-imports # should not use dot imports
      - path: (.+)\.go$
        text: package-comments # package comment should be of the form
      - path: (.+)\.go$
        text: unexported-return # exported func .* returns unexported type .*, which can be annoying to use
      - path: (.+)\.go$
        text: indent-error-flow # if block ends with a return statement, so drop this else and outdent its block
      - path: (.+)\.go$
        text: 'exported: (type|func) name will be used as .* by other packages, and that stutters;'
      - path: (.+)\.go$
        text: exported function Convert_.* should have comment or be unexported
      - path: (.+)\.go$
        text: redundant-import-alias
      - path: (.+)\.go$
        text: 'avoid meaningless package names'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  concurrency: 4

## ci gardener ci infra